// ProjectGenerator.cpp
#include "systems/generation/ProjectGenerator.hpp"
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QRegularExpression>
#include <QTextStream>
#include <algorithm>
namespace {
bool writeFile(const QString& path,const QString& text,QString* error)
{
    /**Writes a complete generated project file.*/
    QFile f(path);if(!f.open(QIODevice::WriteOnly|QIODevice::Text|QIODevice::Truncate)){if(error)*error=f.errorString();return false;}f.write(text.toUtf8());return true;
}
}
namespace pvd {
bool ProjectGenerator::generate(ApplicationState* state,const QHash<QString,QString>& pioPrograms,QString* error)
{
    /**Generates a runnable Pico SDK project from current project state.*/
    if(!state||state->projectPath.isEmpty()){if(error)*error="Create or open a project first.";return false;}
    const QString out=QDir(state->projectPath).filePath("generated");QDir().mkpath(out);QStringList files;const QString ext=state->language=="C"?"c":"cpp";const QString main=QDir(out).filePath("main."+ext);
    if(!writeFile(main,generateMain(*state),error))return false;files<<main;QStringList pioFiles;QHash<QString,QString> normalizedPrograms;const QString fallbackProgram=pioPrograms.value("Mogge",pioPrograms.isEmpty()?QString():pioPrograms.constBegin().value());
    for(const auto& sel:state->selections){
        if(!sel.functionId.startsWith("pio"))continue;
        const QString desired=sel.settings.value("pio_program","Mogge");
        if(normalizedPrograms.contains(desired))continue;
        QString source=pioPrograms.value(desired,fallbackProgram);
        if(source.isEmpty())continue;
        const QString original=pioPrograms.contains(desired)?desired:"Mogge";
        if(original!=desired){source.replace("; "+original+".pio","; "+desired+".pio");source.replace(".program "+original,".program "+desired);}
        const int dead=std::clamp(sel.settings.value("dead_time_cycles","0").toInt(),0,31);
        if(dead>0&&!source.contains("; PVD dead time")){const QString marker=QString("    nop [%1] ; PVD dead time\n").arg(dead);const int wrap=source.indexOf(".wrap\n");if(wrap>=0)source.insert(wrap,marker);else source.append("\n"+marker);}
        normalizedPrograms.insert(desired,source);
    }
    for(auto it=normalizedPrograms.cbegin();it!=normalizedPrograms.cend();++it){const QString p=QDir(out).filePath(it.key()+".pio");if(!writeFile(p,it.value(),error))return false;files<<p;pioFiles<<QFileInfo(p).fileName();}
    const QString lwip=QDir(out).filePath("lwipopts.h");if(!writeFile(lwip,"#pragma once\n#define NO_SYS 1\n#define LWIP_SOCKET 0\n#define LWIP_NETCONN 0\n#define LWIP_RAW 1\n#define LWIP_ARP 1\n#define LWIP_ETHERNET 1\n#define LWIP_ICMP 1\n#define LWIP_DHCP 1\n#define LWIP_DNS 1\n#define LWIP_TCP 1\n#define LWIP_UDP 1\n#define LWIP_TCP_KEEPALIVE 1\n#define LWIP_NETIF_HOSTNAME 1\n#define LWIP_STATS 0\n#define LWIP_PROVIDE_ERRNO 1\n#define LWIP_TIMEVAL_PRIVATE 0\n",error))return false;files<<lwip;
    const QString cmake=QDir(out).filePath("CMakeLists.txt");if(!writeFile(cmake,generateCMake(*state,pioFiles),error))return false;files<<cmake;const QString import=QDir(out).filePath("pico_sdk_import.cmake");if(!writeFile(import,"# pico_sdk_import.cmake\ninclude(\"$ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake\")\n",error))return false;files<<import;const QString info=QDir(out).filePath("information.md");if(!writeFile(info,"<!-- information.md -->\n# Generated by Pico Visual Designer reconstruction\n\nTarget: pico2_w\n",error))return false;files<<info;state->generatedFiles=files;return true;
}
bool ProjectGenerator::validate(const ApplicationState& state,QString* report)
{
    /**Validates that required project and generation inputs are coherent.*/
    QStringList issues;if(state.projectPath.isEmpty())issues<<"Project path is empty.";if(state.projectName.trimmed().isEmpty())issues<<"Project name is empty.";if(state.selections.isEmpty())issues<<"No hardware functions selected.";if(report)*report=issues.isEmpty()?"Validation PASS":issues.join("\n");return issues.isEmpty();
}
QString ProjectGenerator::generateMain(const ApplicationState& state)
{
    /**Generates conservative Pico SDK C/C++ setup code for selected functions.*/
    QString s;
    QTextStream o(&s);
    const bool cpp=state.language!="C";
    o<<(cpp?"// main.cpp\n":"// main.c\n");
    o<<"#include \"pico/stdlib.h\"\n#include \"pico/cyw43_arch.h\"\n#include \"hardware/gpio.h\"\n#include \"hardware/pwm.h\"\n#include \"hardware/uart.h\"\n#include \"hardware/spi.h\"\n#include \"hardware/i2c.h\"\n#include \"hardware/adc.h\"\n#include \"hardware/pio.h\"\n#include \"hardware/clocks.h\"\n#include \"hardware/vreg.h\"\n#include \"hardware/watchdog.h\"\n#include \"pico/multicore.h\"\n\n";
    for(const auto& sel:state.selections)if(sel.functionId.startsWith("pio"))o<<"#include \""<<sel.settings.value("pio_program","Mogge")<<".pio.h\"\n";
    for(const auto& sel:state.selections){if(sel.gpio<0||sel.functionId=="disabled")continue;o<<"#define PIN_"<<sel.physicalPin<<"_GPIO "<<sel.gpio<<"\n";}
    const auto rp2350=state.selections.value("rp2350a");
    const auto rpSetting=[&](const QString& key,const QString& fallback){return rp2350.settings.value(key,fallback);};
    const bool rpEnabled=rp2350.functionId=="rp2350a.configure"&&rpSetting("enabled","true")=="true";
    if(rpEnabled&&rpSetting("core1_enabled","false")=="true")o<<"static void rp2350_core1_entry(void)\n{\n    while (true) { tight_loop_contents(); }\n}\n\n";
    o<<"\nint main(void)\n{\n    /**Initializes generated hardware selections and enters the application loop.*/\n";
    if(rpEnabled){const auto voltage=rpSetting("vreg_voltage","1.10").replace('.','_');const int clock=std::clamp(rpSetting("system_clock_khz","150000").toInt(),0,300000);if(voltage=="0_85"||voltage=="0_90"||voltage=="0_95"||voltage=="1_00"||voltage=="1_05"||voltage=="1_10"||voltage=="1_15"||voltage=="1_20"||voltage=="1_25"||voltage=="1_30")o<<"    vreg_set_voltage(VREG_VOLTAGE_"<<voltage<<");\n";if(clock>0)o<<"    set_sys_clock_khz("<<clock<<", true);\n";if(rpSetting("core1_enabled","false")=="true")o<<"    multicore_launch_core1(rp2350_core1_entry);\n";if(rpSetting("watchdog_enabled","false")=="true")o<<"    watchdog_enable("<<std::clamp(rpSetting("watchdog_timeout_ms","2000").toInt(),1,3600000)<<", true);\n";const int delay=std::clamp(rpSetting("startup_delay_ms","0").toInt(),0,60000);if(delay>0)o<<"    sleep_ms("<<delay<<");\n";}
    o<<"    stdio_init_all();\n";
    if(rpEnabled&&rpSetting("stdio_uart","false")=="true")o<<"    uart_init(uart0, "<<std::clamp(rpSetting("uart_baud","115200").toInt(),1200,4000000)<<");\n";
    auto setting=[&](const FunctionSelection& sel,const QString& key,const QString& fallback){return sel.settings.value(key,fallback);};
    for(const auto& sel:state.selections){
        if(sel.functionId=="disabled"||setting(sel,"enabled","true")!="true")continue;
        if(sel.functionId=="bootsel.use_button"){o<<"    // BOOTSEL is handled by the RP2350 ROM; its selected mode is configured in CMake.\n";}
        else if(sel.functionId=="onboard_led.output"){o<<"    cyw43_arch_init(); cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, "<<(setting(sel,"initial_state","Off")=="On"?"1":"0")<<");\n";}
        else if(sel.functionId=="wireless.cyw43"){const auto mode=setting(sel,"wifi_mode","Station");const auto ssid=setting(sel,"ssid","").replace("\"","\\\"");const auto password=setting(sel,"password","").replace("\"","\\\"");o<<"    cyw43_arch_init();\n";if(mode=="Access Point")o<<"    cyw43_arch_enable_ap_mode(\""<<ssid<<"\", \""<<password<<"\", CYW43_AUTH_WPA2_AES_PSK);\n";else{o<<"    cyw43_arch_enable_sta_mode();\n";o<<"    cyw43_arch_wifi_connect_timeout_ms(\""<<ssid<<"\", \""<<password<<"\", CYW43_AUTH_WPA2_AES_PSK, 30000);\n";}}
        else if(sel.functionId=="gpio.input"){const auto pull=setting(sel,"pull","None");o<<"    gpio_init("<<sel.gpio<<"); gpio_set_dir("<<sel.gpio<<", GPIO_IN);\n";o<<"    gpio_set_pulls("<<sel.gpio<<", "<<(pull=="Pull-up"?"true":"false")<<", "<<(pull=="Pull-down"?"true":"false")<<");\n";}
        else if(sel.functionId=="gpio.output"){const auto level=setting(sel,"initial_state","Low");o<<"    gpio_init("<<sel.gpio<<"); gpio_set_dir("<<sel.gpio<<", GPIO_OUT); gpio_put("<<sel.gpio<<", "<<(level=="High"?"true":"false")<<");\n";o<<"    gpio_set_drive_strength("<<sel.gpio<<", GPIO_DRIVE_STRENGTH_"<<setting(sel,"drive_strength","4")<<"MA);\n";o<<"    gpio_set_slew_rate("<<sel.gpio<<", GPIO_SLEW_RATE_"<<setting(sel,"slew_rate","Fast").toUpper()<<");\n";}
        else if(sel.functionId=="sio"){const auto direction=setting(sel,"direction","Input");const auto pull=setting(sel,"pull","None");o<<"    gpio_init("<<sel.gpio<<"); gpio_set_dir("<<sel.gpio<<", "<<(direction=="Output"?"GPIO_OUT":"GPIO_IN")<<");\n";o<<"    gpio_set_pulls("<<sel.gpio<<", "<<(pull=="Pull-up"?"true":"false")<<", "<<(pull=="Pull-down"?"true":"false")<<");\n";}
        else if(sel.functionId.startsWith("pwm"))o<<"    gpio_set_function("<<sel.gpio<<", GPIO_FUNC_PWM);\n";
        else if(sel.functionId.startsWith("adc")){const int rate=std::max(1,setting(sel,"sample_frequency","1000").toInt());o<<"    adc_init(); adc_gpio_init("<<sel.gpio<<"); adc_select_input("<<std::max(0,sel.gpio-26)<<");\n";o<<"    adc_set_clkdiv(48000000.0f / "<<rate<<".0f);\n";if(setting(sel,"input_mode","Single")=="Continuous")o<<"    adc_fifo_setup(true, true, 1, false, false); adc_run(true);\n";}
        else if(sel.functionId.startsWith("spi")){const auto bus=sel.functionId.startsWith("spi0")?"spi0":"spi1";const int baud=std::max(1,setting(sel,"baud","1000000").toInt());const int bits=std::clamp(setting(sel,"data_bits","8").toInt(),8,16);o<<"    gpio_set_function("<<sel.gpio<<", GPIO_FUNC_SPI);\n";o<<"    spi_init("<<bus<<", "<<baud<<");\n";o<<"    spi_set_format("<<bus<<", "<<bits<<", SPI_CPOL_0, SPI_CPHA_0, SPI_MSB_FIRST);\n";}
        else if(sel.functionId.startsWith("uart")){const auto bus=sel.functionId.startsWith("uart0")?"uart0":"uart1";const int baud=std::max(1,setting(sel,"baud","115200").toInt());const int bits=std::clamp(setting(sel,"data_bits","8").toInt(),5,8);const int stops=std::clamp(setting(sel,"stop_bits","1").toInt(),1,2);o<<"    gpio_set_function("<<sel.gpio<<", GPIO_FUNC_UART);\n";o<<"    uart_init("<<bus<<", "<<baud<<");\n";o<<"    uart_set_format("<<bus<<", "<<bits<<", "<<stops<<", UART_PARITY_NONE);\n";}
        else if(sel.functionId.startsWith("i2c")){const auto bus=sel.functionId.startsWith("i2c0")?"i2c0":"i2c1";const int baud=std::max(1,setting(sel,"baud","100000").toInt());const auto pull=setting(sel,"pull_up","true")=="true";o<<"    gpio_set_function("<<sel.gpio<<", GPIO_FUNC_I2C);\n";o<<"    i2c_init("<<bus<<", "<<baud<<");\n";o<<"    gpio_set_pulls("<<sel.gpio<<", "<<(pull?"true":"false")<<", "<<(pull?"true":"false")<<");\n";}
        else if(sel.functionId.startsWith("pio")){const auto pio=sel.functionId=="pio0"?"pio0":(sel.functionId=="pio1"?"pio1":"pio2");const auto fn=sel.settings.value("pio_program","Mogge");const auto sm=setting(sel,"state_machine","Auto");const auto mode=setting(sel,"operation_mode","Single Pin");const int machine=sm=="Auto"?0:sm.toInt();const int count=std::clamp(setting(sel,"pin_count",mode=="Single Pin"?"1":"8").toInt(),1,32);const int base=std::clamp(setting(sel,"base_pin",QString::number(sel.gpio)).toInt(),0,47);const int threshold=std::clamp(setting(sel,"shift_threshold","32").toInt(),1,32);const auto shift=setting(sel,"shift_direction","Right")=="Right";o<<"    gpio_set_function("<<sel.gpio<<", GPIO_FUNC_"<<sel.functionId.toUpper()<<");\n";o<<"    uint pio_offset_"<<sel.gpio<<" = pio_add_program("<<pio<<", &"<<fn<<"_program);\n";o<<"    for (uint pin = "<<base<<"; pin < "<<base<<" + "<<count<<"; ++pin) pio_gpio_init("<<pio<<", pin);\n";o<<"    pio_sm_config pio_cfg_"<<sel.gpio<<" = "<<fn<<"_program_get_default_config(pio_offset_"<<sel.gpio<<");\n";if(mode=="Multi-Pin Input")o<<"    sm_config_set_in_pins(&pio_cfg_"<<sel.gpio<<", "<<base<<");\n";else if(mode=="Multi-Pin Output")o<<"    sm_config_set_out_pins(&pio_cfg_"<<sel.gpio<<", "<<base<<", "<<count<<");\n";else{o<<"    sm_config_set_in_pins(&pio_cfg_"<<sel.gpio<<", "<<base<<");\n";o<<"    sm_config_set_out_pins(&pio_cfg_"<<sel.gpio<<", "<<base<<", "<<count<<");\n";}o<<"    sm_config_set_in_shift(&pio_cfg_"<<sel.gpio<<", "<<(shift?"true":"false")<<", "<<(setting(sel,"autopush","false")=="true"?"true":"false")<<", "<<threshold<<");\n";o<<"    sm_config_set_out_shift(&pio_cfg_"<<sel.gpio<<", "<<(shift?"true":"false")<<", "<<(setting(sel,"autopull","false")=="true"?"true":"false")<<", "<<threshold<<");\n";o<<"    sm_config_set_clkdiv(&pio_cfg_"<<sel.gpio<<", "<<setting(sel,"clock_divider","1.0")<<");\n";const auto fifo=setting(sel,"fifo_join","None");if(fifo=="RX")o<<"    sm_config_set_fifo_join(&pio_cfg_"<<sel.gpio<<", PIO_FIFO_JOIN_RX);\n";else if(fifo=="TX")o<<"    sm_config_set_fifo_join(&pio_cfg_"<<sel.gpio<<", PIO_FIFO_JOIN_TX);\n";o<<"    pio_sm_init("<<pio<<", "<<machine<<", pio_offset_"<<sel.gpio<<", &pio_cfg_"<<sel.gpio<<");\n";o<<"    pio_sm_set_enabled("<<pio<<", "<<machine<<", true);\n";}
        else if(sel.functionId=="clock_gpin0"||sel.functionId=="clock_gpin1"||sel.functionId.startsWith("clock_gpout"))o<<"    gpio_set_function("<<sel.gpio<<", GPIO_FUNC_GPCK);\n";
        else if(sel.functionId=="hstx")o<<"    gpio_set_function("<<sel.gpio<<", GPIO_FUNC_HSTX);\n";
        else if(sel.functionId=="qmi_cs1n")o<<"    gpio_set_function("<<sel.gpio<<", GPIO_FUNC_XIP_CS1);\n";
        else if(sel.functionId.startsWith("trace"))o<<"    gpio_set_function("<<sel.gpio<<", GPIO_FUNC_CORESIGHT_TRACE);\n";
        else if(sel.functionId.startsWith("usb_"))o<<"    gpio_set_function("<<sel.gpio<<", GPIO_FUNC_USB);\n";
        else if(sel.gpio>=0)o<<"    // "<<sel.functionName<<" uses RP2350 alternate-function mapping on GPIO"<<sel.gpio<<".\n";
    }
    for(const auto& sel:state.selections){
        if(sel.functionId.startsWith("pwm")&&setting(sel,"enabled","true")=="true"){
            o<<"    uint slice_"<<sel.gpio<<" = pwm_gpio_to_slice_num("<<sel.gpio<<");\n";
            o<<"    uint chan_"<<sel.gpio<<" = pwm_gpio_to_channel("<<sel.gpio<<");\n";
            const int frequency=std::max(1,setting(sel,"frequency_hz","25000").toInt());const int duty=std::clamp(setting(sel,"duty_percent","50").toInt(),0,100);const int wrap=std::clamp(setting(sel,"wrap","1000").toInt(),1,65535);const int counter=std::clamp(setting(sel,"counter_start","0").toInt(),0,wrap);const bool phaseCorrect=setting(sel,"phase_correct","false")=="true";const bool invertA=setting(sel,"invert_a","false")=="true";const bool invertB=setting(sel,"invert_b","false")=="true";QString divider=setting(sel,"clock_divider","1.0").trimmed();if(!QRegularExpression("^[0-9]+(\\.[0-9]+)?$").match(divider).hasMatch())divider="1.0";const bool automatic=setting(sel,"timing_mode","Automatic")!="Manual";const QString dividerMode=setting(sel,"divider_mode","Free-running");
            o<<"    pwm_config cfg_"<<sel.gpio<<" = pwm_get_default_config();\n";
            if(automatic)o<<"    pwm_config_set_clkdiv(&cfg_"<<sel.gpio<<", 125000000.0f / ("<<frequency<<".0f * "<<(wrap+1)<<".0f * "<<(phaseCorrect?2:1)<<".0f));\n";else o<<"    pwm_config_set_clkdiv(&cfg_"<<sel.gpio<<", "<<divider<<"f);\n";
            if(dividerMode=="B rises")o<<"    pwm_config_set_clkdiv_mode(&cfg_"<<sel.gpio<<", PWM_DIV_B_RISING);\n";else if(dividerMode=="B high")o<<"    pwm_config_set_clkdiv_mode(&cfg_"<<sel.gpio<<", PWM_DIV_B_HIGH);\n";
            o<<"    pwm_config_set_phase_correct(&cfg_"<<sel.gpio<<", "<<(phaseCorrect?"true":"false")<<");\n";
            o<<"    pwm_config_set_output_polarity(&cfg_"<<sel.gpio<<", "<<(invertA?"true":"false")<<", "<<(invertB?"true":"false")<<");\n";
            o<<"    pwm_config_set_wrap(&cfg_"<<sel.gpio<<", "<<wrap<<");\n";
            o<<"    pwm_init(slice_"<<sel.gpio<<", &cfg_"<<sel.gpio<<", true);\n";
            o<<"    pwm_set_counter(slice_"<<sel.gpio<<", "<<counter<<");\n";
            o<<"    pwm_set_chan_level(slice_"<<sel.gpio<<", chan_"<<sel.gpio<<", (uint16_t)(((uint32_t)"<<wrap<<" * "<<duty<<") / 100u));\n";
            o<<"    pwm_set_enabled(slice_"<<sel.gpio<<", "<<(setting(sel,"enabled","true")=="true"?"true":"false")<<");\n";
        }
    }
    o<<"\n    while (true) {\n";
    if(rpEnabled&&rpSetting("watchdog_enabled","false")=="true")o<<"        watchdog_update();\n";
    o<<"        tight_loop_contents();\n    }\n}\n";
    return s;
}
QString ProjectGenerator::generateCMake(const ApplicationState& state,const QStringList& pioFiles)
{
    /**Generates Pico SDK CMake integration for the selected language and PIO programs.*/
    QString s;QTextStream o(&s);const QString ext=state.language=="C"?"c":"cpp";QString target=state.projectName;target.replace(QRegularExpression("[^A-Za-z0-9_]"),"_");if(target.isEmpty())target="PICO2W";const auto rp2350=state.selections.value("rp2350a");const bool usb=rp2350.settings.value("stdio_usb","true")=="true";const bool uart=rp2350.settings.value("stdio_uart","false")=="true";const int uartBaud=std::clamp(rp2350.settings.value("uart_baud","115200").toInt(),1200,4000000);o<<"# CMakeLists.txt\ncmake_minimum_required(VERSION 3.13)\ninclude(pico_sdk_import.cmake)\nproject("<<target<<" LANGUAGES C CXX ASM)\nset(CMAKE_C_STANDARD 11)\nset(CMAKE_CXX_STANDARD 17)\npico_sdk_init()\nadd_executable("<<target<<" main."<<ext<<")\ntarget_link_libraries("<<target<<" pico_stdlib pico_multicore hardware_gpio hardware_pwm hardware_uart hardware_spi hardware_i2c hardware_adc hardware_pio pico_cyw43_arch_lwip_threadsafe_background pico_lwip_nosys)\n";for(const auto& sel:state.selections)if(sel.functionId=="bootsel.use_button"&&sel.settings.value("mode","Press")!="Press"){const int timeout=std::clamp(sel.settings.value("debounce_ms","50").toInt(),1,10000);o<<"target_link_libraries("<<target<<" pico_bootsel_via_double_reset)\ntarget_compile_definitions("<<target<<" PRIVATE PICO_BOOTSEL_VIA_DOUBLE_RESET_TIMEOUT_MS="<<timeout<<")\n";}o<<"target_include_directories("<<target<<" PRIVATE ${CMAKE_CURRENT_LIST_DIR})\n";for(const auto& p:pioFiles)o<<"pico_generate_pio_header("<<target<<" ${CMAKE_CURRENT_LIST_DIR}/"<<p<<")\n";o<<"pico_enable_stdio_usb("<<target<<" "<<(usb?1:0)<<")\npico_enable_stdio_uart("<<target<<" "<<(uart?1:0)<<")\n";if(uart)o<<"target_compile_definitions("<<target<<" PRIVATE PVD_UART_BAUD="<<uartBaud<<")\n";o<<"pico_add_extra_outputs("<<target<<")\n";return s;
}
}
