# multicore_gdb_gui_cert.ps1
param([string]$Executable="build-current/pico_visual_designer.exe",[string]$Database="validation/rp2350_multicore_debug_project/PVD_RP2350_MULTICORE_DEBUG.sqlite",[string]$ResultPath="validation/pin_certification/results/multicore-gdb-gui-20260825.json")
$ErrorActionPreference="Stop";Import-Module (Join-Path $PSScriptRoot "PvdGuiAutomation.psm1") -Force
function C($r,[string]$id){$r.FindAll([System.Windows.Automation.TreeScope]::Descendants,[System.Windows.Automation.Condition]::TrueCondition)|Where-Object{$_.Current.AutomationId -eq $id -or $_.Current.AutomationId.EndsWith("."+$id)}|Select-Object -First 1}
function I($x){[void]$x.GetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern).Invoke()}
function T($x){try{$x.GetCurrentPattern([System.Windows.Automation.ValuePattern]::Pattern).Current.Value}catch{$x.Current.Name}}
function Send($cmd,$commandControl,$button){$commandControl.GetCurrentPattern([System.Windows.Automation.ValuePattern]::Pattern).SetValue($cmd);I $button;Start-Sleep -Seconds 2}
$p=$null;$r=[ordered]@{result="FAIL";stages=[ordered]@{}}
try {
 $r.log_tail="diagnostic started"
 Get-Process pico_visual_designer,openocd,arm-none-eabi-gdb -ErrorAction SilentlyContinue|Stop-Process -Force -ErrorAction SilentlyContinue
 $p=Start-Process -FilePath (Resolve-Path $Executable).Path -ArgumentList "--certification-dialogs" -PassThru;Start-Sleep 2;$w=Get-PvdWindow $p.Id;I(C $w "project_open");$d=Wait-PvdElement (Get-PvdWindow $p.Id) "pvd_automation_file_dialog" "";$f=C $d "fileNameEdit";$f.GetCurrentPattern([System.Windows.Automation.ValuePattern]::Pattern).SetValue((Resolve-Path $Database).Path);$open=@($d.FindAll([System.Windows.Automation.TreeScope]::Descendants,[System.Windows.Automation.Condition]::TrueCondition)|Where-Object{$_.Current.Name -eq "Open"})|Select-Object -First 1;I $open;Start-Sleep 2;Navigate-PvdPage $p.Id "Debug"|Out-Null
 $w=Get-PvdWindow $p.Id;$ids=@("debug_status","debug_start","debug_stop","debug_halt","debug_continue","debug_step","debug_next","debug_backtrace","debug_registers","debug_command","debug_send_command","debug_log","debug_core_selector");$c=@{};foreach($id in $ids){$c[$id]=C $w $id;if(-not$c[$id]){throw "Missing $id"}}
 I $c.debug_start;$deadline=(Get-Date).AddSeconds(25);while((Get-Date)-lt$deadline){if((T $c.debug_log)-match "RP2350 core mapping resolved"){break};Start-Sleep -Milliseconds 250};$log=T $c.debug_log;$freshSelector=Find-PvdControlFresh $p.Id "debug_core_selector" "" 5;$r.stages.StartConnect=if($log -match "Remote debugging using localhost:3333"){"PASS"}else{"FAIL"};$r.stages.SelectorEnabled=if($freshSelector.Current.IsEnabled){"PASS"}else{"FAIL"};$r.stages.Core0Selector=if((T $freshSelector) -eq "Core 0"){"PASS"}else{"FAIL"}
 Send "info threads" $c.debug_command $c.debug_send_command;Send "info registers" $c.debug_command $c.debug_send_command;Send "bt" $c.debug_command $c.debug_send_command;Send "p core0_debug_counter" $c.debug_command $c.debug_send_command;$log=T $c.debug_log;$r.stages.Core0Application=if($log -match "pvd_core0_runtime_handler_0|core0_debug_counter"){"PASS"}else{"FAIL"};$r.stages.Core0Registers=if($log -match "r0\s+0x"){"PASS"}else{"FAIL"};Send "break pvd_core0_runtime_handler_0" $c.debug_command $c.debug_send_command;Send "continue" $c.debug_command $c.debug_send_command;Start-Sleep 1;I $c.debug_halt;Start-Sleep 2;$log=T $c.debug_log;$r.stages.Core0Breakpoint=if($log -match "Breakpoint [0-9]+.*pvd_core0_runtime_handler_0|pvd_core0_runtime_handler_0"){"PASS"}else{"FAIL"}
 $freshSelector=Find-PvdControlFresh $p.Id "debug_core_selector" "" 5;Select-PvdComboItemAsUser $freshSelector "Core 1" $p.Id | Out-Null;Start-Sleep -Milliseconds 300;$freshSelector=Find-PvdControlFresh $p.Id "debug_core_selector" "" 5;$r.stages.Core1Selector=if((T $freshSelector) -eq "Core 1"){"PASS"}else{"FAIL"};Send "info registers" $c.debug_command $c.debug_send_command;Send "bt" $c.debug_command $c.debug_send_command;Send "p core1_debug_counter" $c.debug_command $c.debug_send_command;$log=T $c.debug_log;$r.stages.Core1Application=if($log -match "rp2350_core1_entry|pvd_runtime_handler_0|core1_debug_counter"){"PASS"}else{"FAIL"};$r.stages.Core1Registers=if($log -match "r0\s+0x"){"PASS"}else{"FAIL"};Send "break pvd_runtime_handler_0" $c.debug_command $c.debug_send_command;Send "continue" $c.debug_command $c.debug_send_command;Start-Sleep 1;I $c.debug_halt;Start-Sleep 2;$log=T $c.debug_log;$r.stages.Core1Breakpoint=if($log -match "Breakpoint [0-9]+.*pvd_runtime_handler_0|pvd_runtime_handler_0"){"PASS"}else{"FAIL"};$freshSelector=Find-PvdControlFresh $p.Id "debug_core_selector" "" 5;Select-PvdComboItemAsUser $freshSelector "Core 0" $p.Id | Out-Null;Start-Sleep -Milliseconds 300;$r.stages.Core0Return=if((T (Find-PvdControlFresh $p.Id "debug_core_selector" "" 5)) -eq "Core 0"){"PASS"}else{"FAIL"}
 Send "p core0_debug_counter" $c.debug_command $c.debug_send_command;Send "p core1_debug_counter" $c.debug_command $c.debug_send_command;$log=T $c.debug_log;$r.stages.Counters=if($log -match "core0_debug_counter" -and $log -match "core1_debug_counter"){"PASS"}else{"FAIL"};Send "info threads" $c.debug_command $c.debug_send_command;$log=T $c.debug_log;$r.stages.ThreadMapping=if($log -match "rp2350.cm0" -and $log -match "rp2350.cm1"){"PASS"}else{"FAIL"};$r.log_tail=$log.Substring([Math]::Max(0,$log.Length-12000));$r.stages.GuiControls="PASS";I $c.debug_stop;Start-Sleep 3;$r.stages.Cleanup=if(-not(Get-Process openocd,arm-none-eabi-gdb -ErrorAction SilentlyContinue)){"PASS"}else{"FAIL"};$r.result=if(($r.stages.Values|Where-Object{$_ -eq "FAIL"}).Count -eq 0){"PASS"}else{"FAIL"}
}catch{$r.failure=$_.Exception.Message}finally{if($p-and-not$p.HasExited){$p.CloseMainWindow();Start-Sleep 1;if(-not$p.HasExited){$p.Kill()}};Get-Process openocd,arm-none-eabi-gdb -ErrorAction SilentlyContinue|Stop-Process -Force -ErrorAction SilentlyContinue};$parent=Split-Path -Parent $ResultPath;if($parent){New-Item -ItemType Directory -Force -Path $parent|Out-Null};$r|ConvertTo-Json -Depth 8|Set-Content -Encoding UTF8 $ResultPath;$r|ConvertTo-Json -Depth 8
