"""Generate the reusable Pico 2 W physical-pin certification protocol.

The legacy pins 1-5 protocol is read-only input. Function inventories are
discovered from PVD's per-function SQLite databases; this generator does not
maintain a second function list.
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
from pathlib import Path


ROOT = Path(__file__).parent
REPO = ROOT.parent.parent
LEGACY = REPO / "validation" / "test_1_to_5"
FUNCTION_ROOT = REPO / "src" / "systems" / "components" / "pin_functions"
STAGES = [
    "launch", "navigation", "selection", "settings", "save_persistence",
    "generate", "configure", "build", "transfer", "runtime", "debug",
    "physical", "cleanup",
]
PIN_MAP = {1: 0, 2: 1, 3: None, 4: 2, 5: 3, 6: 4, 7: 5, 8: None, 9: 6, 10: 7}
PAIR_MAP = {
    "pair_a": ["gpio0", "gpio1"],
    "pair_b": ["gpio2", "gpio3"],
    "pair_c": ["gpio4", "gpio5"],
    "pair_d": ["gpio6", "gpio7"],
}
SDK_FAMILY = {
    "I2C": "GPIO_FUNC_I2C", "PIO": "GPIO_FUNC_PIO0/1/2", "PWM": "GPIO_FUNC_PWM",
    "SIO": "GPIO_FUNC_SIO", "SPI": "GPIO_FUNC_SPI", "UART": "GPIO_FUNC_UART",
    "Trace": "GPIO_FUNC_CORESIGHT_TRACE", "USB": "GPIO_FUNC_USB",
}
GENERATOR_CATEGORIES = {"I2C", "PIO", "PWM", "SIO", "SPI", "UART", "Trace", "USB", "QMI"}


def load_jsonc(path: Path) -> dict:
    lines = [line for line in path.read_text(encoding="utf-8").splitlines()
             if not line.lstrip().startswith("//")]
    return json.loads("\n".join(lines))


def write_jsonc(path: Path, value: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("// Generated by generate_protocol.py; do not hand-edit.\n" +
                    json.dumps(value, indent=2) + "\n", encoding="utf-8")


def stages(enabled: bool = True, physical: bool = False, reason: str = "", physical_reason: str = "") -> dict:
    result = {}
    for stage in STAGES:
        active = enabled
        why = reason if not enabled else ""
        if stage in {"transfer", "runtime", "debug"}:
            active = False
            why = "Physical campaign execution is gated pending pre-execution report approval."
        if stage == "physical":
            active = physical and enabled
            why = physical_reason if not active and physical_reason else ("Requires approved physical execution batch and connected rig." if not active else "")
        result[stage] = {"should_test": active, "result": "NOT-RUN", "disabled_reason": why}
    return result


def metadata(db: Path) -> tuple[dict[str, str], list[int]]:
    with sqlite3.connect(db) as connection:
        values = dict(connection.execute("SELECT key, value FROM metadata"))
        pins = [row[0] for row in connection.execute("SELECT gpio FROM pin_mappings ORDER BY gpio")]
    return values, pins


def function_inventory() -> dict[int, list[dict]]:
    inventory = {gpio: [] for gpio in range(8)}
    for db in sorted(FUNCTION_ROOT.glob("*/function.sqlite")):
        values, pins = metadata(db)
        for gpio in pins:
            if gpio not in inventory:
                continue
            category = values["category"]
            selector = SDK_FAMILY.get(category, "NOT_APPLICABLE")
            if values["function_id"].endswith("_aux"):
                selector = "GPIO_FUNC_UART_AUX"
            inventory[gpio].append({
                "pvd_function_id": values["function_id"],
                "hardware_function": values["display_name"],
                "category": category,
                "sdk_selector_family": selector,
                "hardware_supported": True,
                "pvd_supported": True,
                "generator_supported": category in GENERATOR_CATEGORIES,
                "protocol_present": True,
                "should_test": True,
                "physical_test_feasible": category in {"SIO", "PWM", "PIO"},
                "discrepancy_class": "MATCH",
                "source_database": str(db.relative_to(REPO)).replace("\\", "/"),
            })
    return inventory


def requirements(category: str) -> list[str]:
    common = ["visible_selection", "save_persistence", "generated_configuration", "build", "debug_state"]
    specific = {
        "SIO": ["direction", "initial_level", "high_low", "input_readback", "pull_settings", "persistence"],
        "PWM": ["slice", "channel", "frequency", "duty", "wrap_top", "divider", "phase_correct", "inversion", "ownership"],
        "PIO": ["block", "state_machine", "instruction_memory", "offset", "pin_mapping", "clock_divider", "shift", "fifo", "wrap", "ownership"],
        "UART": ["instance", "role", "baud", "data_format", "pin_mapping", "ownership"],
        "SPI": ["instance", "role", "clock", "data_format", "pin_mapping", "ownership"],
        "I2C": ["instance", "role", "clock", "addressing", "pullups", "ownership"],
        "Trace": ["trace_role", "debug_capture", "pin_mapping"],
        "QMI": ["qmi_role", "pin_mapping", "ownership", "special_equipment"],
        "USB": ["usb_role", "pin_mapping", "special_equipment"],
    }
    return common + specific.get(category, ["pin_mapping", "ownership"])


def function_case(pin: int, gpio: int, item: dict) -> dict:
    fid = item["pvd_function_id"]
    category = item["category"]
    physical = item["physical_test_feasible"]
    physical_reason = {
        "I2C": "Requires external I2C target with open-drain bus behavior and valid pull-ups; the 1180 ohm GPIO links are not an I2C bus.",
        "UART": "UART role validation remains in the protocol; a campaign-level TX/RX pairing must be approved before execution.",
        "SPI": "The fixed pairs do not provide a complete valid SPI TX/RX/SCK/CSn topology without rewiring; keep physical execution disabled.",
        "Trace": "Requires trace capture setup and dedicated trace-capable debug equipment.",
        "USB": "Requires a USB power/control test fixture and board-specific USB validation setup.",
        "QMI": "Requires QMI/XIP-specific hardware and safe flash/PSRAM test setup.",
    }.get(category, "")
    return {
        "test_id": f"P{pin:02d}-{fid.upper()}",
        "name": f"Physical pin {pin} / GPIO{gpio}: {item['hardware_function']}",
        "category": category,
        "physical_pin": pin,
        "gpio": gpio,
        "hardware_function": fid,
        "hardware_function_name": item["hardware_function"],
        "sdk_selector_family": item["sdk_selector_family"],
        "hardware_supported": item["hardware_supported"],
        "pvd_supported": item["pvd_supported"],
        "generator_supported": item["generator_supported"],
        "protocol_present": item["protocol_present"],
        "should_test": True,
        "disabled_reason": "",
        "expected_pvd_support": "CONFIRMED_PVD_SOURCE_OF_TRUTH",
        "requires_external_hardware": category in {"I2C", "Trace", "USB"},
        "physical_test_feasible": physical,
        "source_database": item["source_database"],
        "discrepancy_class": item["discrepancy_class"],
        "requirements": requirements(category),
        "stages": stages(physical=physical, physical_reason=physical_reason),
    }


def gnd_case(pin: int, suffix: str, name: str, req: list[str]) -> dict:
    return {
        "test_id": f"P{pin:02d}-GND-{suffix}", "name": f"Physical pin {pin} / GND: {name}",
        "category": "GND", "physical_pin": pin, "gpio": None,
        "hardware_function": "gnd", "hardware_function_name": "GND",
        "sdk_selector_family": "NOT_APPLICABLE", "hardware_supported": True,
        "pvd_supported": True, "generator_supported": True, "protocol_present": True,
        "should_test": True, "disabled_reason": "", "expected_pvd_support": "NOT_PROGRAMMABLE",
        "requires_external_hardware": False, "physical_test_feasible": False,
        "source_database": "src/systems/components/PicoPinMap.cpp",
        "discrepancy_class": "NOT_A_MUX_FUNCTION", "requirements": req,
        "stages": stages(physical=False),
    }


def negative_case(test_id: str, name: str, category: str, req: list[str], reason: str = "") -> dict:
    return {
        "test_id": test_id, "name": name, "category": category, "physical_pin": None, "gpio": None,
        "hardware_function": "negative", "hardware_function_name": name,
        "sdk_selector_family": "NOT_APPLICABLE", "hardware_supported": True,
        "pvd_supported": True, "generator_supported": True, "protocol_present": True,
        "should_test": True, "disabled_reason": "", "expected_pvd_support": "NOT_APPLICABLE",
        "requires_external_hardware": False, "physical_test_feasible": False,
        "source_database": "PVD GUI conflict validation and generator validation",
        "discrepancy_class": "NOT_A_MUX_FUNCTION", "requirements": req,
        "stages": stages(physical=False),
    }


def sio_campaign() -> list[dict]:
    pairs = [("A", 0, 1), ("B", 2, 3), ("C", 4, 5), ("D", 6, 7)]
    result = []
    for label, output, input_gpio in pairs:
        for direction, source, sink in (("FWD", output, input_gpio), ("REV", input_gpio, output)):
            result.append({
                "test_id": f"SIO-PAIR-{label}-{direction}",
                "name": f"SIO physical loopback pair {label}: GPIO{source} output to GPIO{sink} input",
                "category": "SIO_PHYSICAL_BASELINE", "physical_pin": None, "gpio": source,
                "paired_gpio": sink, "hardware_function": "sio", "hardware_function_name": "SIO",
                "sdk_selector_family": "GPIO_FUNC_SIO", "hardware_supported": True,
                "pvd_supported": True, "generator_supported": True, "protocol_present": True,
                "should_test": True, "disabled_reason": "", "expected_pvd_support": "CONFIRMED_PVD_SOURCE_OF_TRUTH",
                "requires_external_hardware": False, "physical_test_feasible": True,
                "source_database": "src/systems/components/pin_functions/sio/function.sqlite",
                "discrepancy_class": "MATCH",
                "requirements": ["real_gui", "selection", "direction", "initial_low", "high", "low", "input_readback", "pull_settings", "persistence", "generate", "configure", "build", "transfer", "runtime", "debug", "physical_loopback", "no_opposing_outputs"],
                "rig_pair": f"pair_{label.lower()}", "series_resistance_ohm": 1180,
                "stages": {stage: {"should_test": True, "result": "NOT-RUN", "disabled_reason": ""} for stage in STAGES},
            })
    return result


def main() -> int:
    inventory = function_inventory()
    for gpio in range(8):
        if not inventory[gpio]:
            raise RuntimeError(f"No PVD SQLite functions discovered for GPIO{gpio}")
    for path in ROOT.glob("groups/pins_01_10/pin_*.jsonc"):
        path.unlink()
    for gpio, pin in ((4, 6), (5, 7), (6, 9), (7, 10)):
        tests = [function_case(pin, gpio, item) for item in inventory[gpio]]
        write_jsonc(ROOT / "groups" / "pins_01_10" / f"pin_{pin:02d}_gpio{gpio}.jsonc", {
            "physical_pin": pin, "gpio": gpio, "pin_type": "GPIO", "source_of_truth": "PVD SQLite catalog + PicoPinMap.cpp", "tests": tests,
        })
    gnd_tests = [
        gnd_case(8, "CLASSIFICATION", "classification", ["pin_type_gnd", "programmable_no"]),
        gnd_case(8, "REJECT-FUNCTION", "programmable function rejection", ["reject_gpio", "reject_peripheral_mux", "gui_prevents_invalid_configuration"]),
        gnd_case(8, "PERSISTENCE", "non-programmable persistence", ["save_persistence", "reload", "preserve_gnd"]),
        gnd_case(8, "GENERATOR", "no GPIO initialization emitted", ["generate", "configure", "no_gpio_initialization"]),
    ]
    write_jsonc(ROOT / "groups" / "pins_01_10" / "pin_08_gnd.jsonc", {"physical_pin": 8, "gpio": None, "pin_type": "GND", "programmable": False, "source_of_truth": "PicoPinMap.cpp", "tests": gnd_tests})
    conflicts = [
        ("NEG-INVALID-FUNCTION", "Invalid GPIO function is rejected", "INVALID_FUNCTION", ["gui_rejection", "generator_rejection"]),
        ("NEG-DUPLICATE-GPIO", "Duplicate GPIO ownership is rejected", "RESOURCE_CONFLICT", ["gui_conflict", "ownership"]),
        ("NEG-PWM-CHANNEL", "PWM slice/channel conflict is rejected", "RESOURCE_CONFLICT", ["gui_conflict", "slice", "channel"]),
        ("NEG-PWM-SLICE", "PWM slice-wide configuration conflict is rejected", "RESOURCE_CONFLICT", ["gui_conflict", "slice_wide_settings"]),
        ("NEG-PIO-SM", "PIO state-machine conflict is rejected", "RESOURCE_CONFLICT", ["gui_conflict", "pio_block", "state_machine"]),
        ("NEG-PIO-MEMORY", "PIO instruction-memory conflict is rejected", "RESOURCE_CONFLICT", ["gui_conflict", "instruction_memory"]),
        ("NEG-UART", "UART ownership conflict is rejected", "RESOURCE_CONFLICT", ["gui_conflict", "uart_ownership"]),
        ("NEG-SPI", "SPI ownership conflict is rejected", "RESOURCE_CONFLICT", ["gui_conflict", "spi_ownership"]),
        ("NEG-I2C", "I2C ownership conflict is rejected", "RESOURCE_CONFLICT", ["gui_conflict", "i2c_ownership"]),
        ("NEG-GND", "GND cannot be programmed", "GND_REJECTION", ["gui_rejection", "non_programmable"]),
    ]
    write_jsonc(ROOT / "groups" / "pins_01_10" / "block_negative.jsonc", {"scope": "pins_01_10", "tests": [negative_case(f"BLOCK-{tid}", name, cat, req) for tid, name, cat, req in conflicts]})
    write_jsonc(ROOT / "groups" / "pins_01_10" / "sio_baseline.jsonc", {"scope": "pins_01_10", "physical_rig": {"pair_a": PAIR_MAP["pair_a"], "pair_b": PAIR_MAP["pair_b"], "pair_c": PAIR_MAP["pair_c"], "pair_d": PAIR_MAP["pair_d"], "series_resistance_ohm": 1180, "debugger": ["SWDIO", "GND", "SWCLK"], "debugger_uses_header_pins_1_3": False}, "tests": sio_campaign()})
    legacy_files = sorted(LEGACY.rglob("*.jsonc"))
    legacy_hashes = {str(p.relative_to(REPO)).replace("\\", "/"): hashlib.sha256(p.read_bytes()).hexdigest() for p in legacy_files}
    legacy_manifest = load_jsonc(LEGACY / "manifest.jsonc")
    write_jsonc(ROOT / "legacy_traceability.jsonc", {"source": "validation/test_1_to_5", "preserved_byte_hashes": legacy_hashes, "test_ids": [entry["test_id"] for entry in legacy_manifest["tests"]], "test_count": legacy_manifest["test_count"]})
    hardware = {"authority": "RP2350 datasheet GPIO Bank 0 table + Pico SDK gpio_function_rp2350 + PVD SQLite", "sources": ["https://datasheets.raspberrypi.com/rp2350/rp2350-datasheet.pdf", "https://github.com/raspberrypi/pico-sdk/tree/2.3.0/src/rp2350", "https://github.com/raspberrypi/pico-sdk/blob/2.3.0/src/boards/include/boards/pico2_w.h", "src/systems/components/PicoPinMap.cpp"], "gpio": {str(g): inventory[g] for g in range(8)}, "hardware_only": [], "pvd_only": [], "generator_gaps": [], "uncertain": []}
    write_jsonc(ROOT / "hardware_reference.jsonc", hardware)
    write_jsonc(ROOT / "protocol.jsonc", {"protocol_id": "pvd-pico2w-pin-certification", "version": 2, "campaign_started": False, "physical_certification_claimed": False, "current_scope": "pins_01_10", "future_groups": ["pins_11_20", "pins_21_30", "pins_31_40"], "legacy_protocol": "validation/test_1_to_5", "pin_map": {str(pin): (f"GPIO{gpio}" if gpio is not None else "GND") for pin, gpio in PIN_MAP.items()}, "pin_types": ["GPIO", "GND", "POWER", "ADC", "AGND", "RUN_CONTROL", "DEBUG", "SPECIAL"], "canonical_stages": STAGES, "result_vocabulary": ["PASS-CORE", "PASS-GUI", "PASS-GENERATE", "PASS-CONFIGURE", "PASS-BUILD", "PASS-TRANSFER", "PASS-RUNTIME", "PASS-DEBUG", "PASS-AUTOMATED", "PASS-PHYSICAL", "NOT-TESTED", "NOT-APPLICABLE", "REQUIRES-EXTERNAL-HARDWARE", "FAIL"], "physical_rig": {"pair_a": ["gpio0", "gpio1"], "pair_b": ["gpio2", "gpio3"], "pair_c": ["gpio4", "gpio5"], "pair_d": ["gpio6", "gpio7"], "series_resistance_ohm": 1180, "debugger": ["SWDIO", "GND", "SWCLK"], "debugger_uses_header_pins_1_3": False}, "execution_policy": {"real_gui_required": True, "physical_execution_gate": "pre-execution-report-review", "pins_11_40_execution": False, "i2c_resistor_link_is_not_bus": True}})
    all_tests = legacy_manifest["test_count"] + sum(len(load_jsonc(p)["tests"]) for p in (ROOT / "groups/pins_01_10").glob("pin_*.jsonc")) + len(load_jsonc(ROOT / "groups/pins_01_10/block_negative.jsonc")["tests"]) + len(load_jsonc(ROOT / "groups/pins_01_10/sio_baseline.jsonc")["tests"])
    manifest_tests = []
    for entry in legacy_manifest["tests"]:
        manifest_tests.append({**entry, "source": "validation/test_1_to_5"})
    for path in sorted((ROOT / "groups/pins_01_10").glob("*.jsonc")):
        if path.name in {"sio_baseline.jsonc", "block_negative.jsonc"}:
            continue
        for test in load_jsonc(path)["tests"]:
            manifest_tests.append({"test_id": test["test_id"], "source": str(path.relative_to(ROOT)).replace("\\", "/")})
    for filename in ("block_negative.jsonc", "sio_baseline.jsonc"):
        for test in load_jsonc(ROOT / "groups/pins_01_10" / filename)["tests"]:
            manifest_tests.append({"test_id": test["test_id"], "source": f"groups/pins_01_10/{filename}"})
    write_jsonc(ROOT / "manifest.jsonc", {"protocol_id": "pvd-pico2w-pin-certification", "test_count": all_tests, "legacy_test_count": legacy_manifest["test_count"], "new_test_count": all_tests - legacy_manifest["test_count"], "stage_count": len(STAGES), "tests": manifest_tests})
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
